### PR TITLE
Update let's encrypt by adding sleep

### PR DESCRIPTION
**Pull request by jakubknejzlik**
This changes are required (in my case) to successfuly generate LE certificates.

### CODE REVIEW

**Comment by adi90x** [comment]
Hello, 
Don't really understand what it could change to add a 30s sleep to this script

**Comment by jakubknejzlik** [comment]
Hello @adi90x, in my case the response for acme challenge is 503 (maybe the nginx can't update it's config "in time"). After 30s delay (maybe 10s could be enough) is everything correctly updated and le certificates are successfully generated.

**Comment by jakubknejzlik** [comment]
Looks like I can't :)
```
Only those with write access to this repository can merge pull requests.
```

**Comment by adi90x** [comment]
Arf I guess you need to have an account on gitlab.com to send pull request as I have set everything to public normaly ! 
Don't worry , i will do it tonight

**Comment by adi90x** [comment]
i just commit it on gitlab ( however seems that I have a problem on the workflow , not related to that => I am looking into it now ! )

**Comment by adi90x** [comment]
Pull request add on gitlab side , workflow is working and image is rebuilding on docker hub ! 
Thanks a lot for the PR , do not hesitate to submit any other modification !

**Pull request closed without merging**
