### PR TITLE
"source letsencrypt.conf" was missing

### PR DESCRIPTION
**Pull request by qulo**

### CODE REVIEW

**Comment by adi90x** [comment]
Thanks a lot I delete it with previous commit and didn't notice it !

**Comment by adi90x** [comment]
However, could you send PR request to `https://gitlab.com/adi90x/rancher-active-proxy.git` next time ? 
As it is easier for me to merge there  ( here it is just a mirror repo of gitlab repo)

**Comment by qulo** [comment]
Yes I will send the next PR directly to gitlab. Thank for the quick response, this bug was giving me a hard time yesterday ;) 

Cheers

**Comment by adi90x** [comment]
Yes, I guess it was a really annoying and difficult error to spot,  I
really need to setup some CI test to avoid that,  however to test again
rancher api it is quite difficult to build...

**Pull request merged**
